export function NavCollectionButton({
  onClick,
  isDarkMode,
}: {
  onClick: () => void;
  isDarkMode: boolean;
}) {
  return (
    <div
      className={`absolute h-[50px] left-[30px] top-[25px] w-[90px] rounded-[20px] cursor-pointer transition-colors
        ${isDarkMode ? "bg-gray-800 hover:bg-gray-700" : "bg-white hover:bg-gray-50"}`}
      onClick={onClick}
    >
      <div
        aria-hidden="true"
        className="absolute inset-0 rounded-[20px] border border-[#83aaff] border-solid pointer-events-none"
      />

      {/* All decorative bars (unchanged, still generated by Figma) */}
      {[10, 17.86, 25.71, 33.57, 40.71, 47.86].map((left, idx) => (
        <div
          key={idx}
          className="absolute flex items-center justify-center"
          style={{
            left,
            top: "4.12px",
            height: `calc(1px * ((41.234375*1) + (3.5625*0)))`,
            width: `calc(1px * ((3.5625*1) + (41.234375*0)))`,
            transformOrigin: "center",
          }}
        >
          <div className="flex-none rotate-[90deg]">
            <div className="relative h-[3.571px] w-[41.237px] rounded-[20px] bg-white">
              <div
                aria-hidden="true"
                className="absolute inset-0 rounded-[20px] border border-[#83aaff] border-solid pointer-events-none"
              />
            </div>
          </div>
        </div>
      ))}

      {/* The weird angled final bar */}
      <div
        className="absolute flex items-center justify-center"
        style={{
          left: "54.29px",
          top: "4.12px",
          height: `calc(1px * ((42.859375*0.9585) + (3.53125*0.153)))`,
          width: `calc(1px * ((3.53125*0.988) + (42.859375*0.285)))`,
          transformOrigin: "center",
        }}
      >
        <div className="flex-none rotate-[73.443deg] skew-x-[352.314deg]">
          <div className="relative h-[3.534px] w-[42.868px] rounded-[20px] bg-white">
            <div
              aria-hidden="true"
              className="absolute inset-0 rounded-[20px] border border-[#83aaff] border-solid pointer-events-none"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
